### ISSUE TITLE
"Forced" lowercase/other formatting for discord pronouns?

### ISSUE THREAD

**Issue by jadelily18** [Penguin-Spy/replugged-pronoundb#5]
I was just going to message you on Discord so I didn't clutter up the issues here for no reason, but Discord didn't let me D:

do you think it would be a good idea to allow formatting pronouns as all lowercase, pascal case, etc? right now, it's up to each user to format their own pronouns and the inconsistency irks me lol

**Comment by Penguin-Spy** [comment]
sure, i can add an option to apply the formatting to discord pronouns too.
also i had DMs turned off on all the servers i'm in (they're back on now), but i don't mind using github issues for feature requests :)

**Comment by jadelily18** [comment]
> sure, i can add an option to apply the formatting to discord pronouns too. also i had DMs turned off on all the servers i'm in (they're back on now), but i don't mind using github issues for feature requests :)

wooo! awesome thank you :D

**Comment by Penguin-Spy** [comment]
Implemented in 15b311d, it'll take a moment for the changes to get reviewed.

**Comment by jadelily18** [comment]
> Implemented in [15b311d](https://github.com/Penguin-Spy/replugged-pronoundb/commit/15b311d356a839d85ad1e0e422d8c9aa8ce4a576), it'll take a moment for the changes to get reviewed.

that was way faster than i expected woah lol
