### ISSUE TITLE
CSS not injected

### ISSUE THREAD

**Issue by Leo40Git** [Penguin-Spy/replugged-pronoundb#9]
See title.
![image](https://github.com/Penguin-Spy/replugged-pronoundb/assets/7997354/935d4371-a9ea-4a96-b5c2-3aefe1a9bfb3)

**Comment by Leo40Git** [comment]
Copying the CSS into my Quick CSS works for now.

**Comment by Penguin-Spy** [comment]
cannot reproduce, is the issue consistent or does it only happen intermittently? does reloading sometimes fix it?
if it's inconsistent it may be a Replugged issue, there's been some general loading issues recently.

**Comment by Leo40Git** [comment]
Hm, this seems to happen at random even without the DevtoolsBandage plugin. Might just be Replugged in general being a bit unstable right now, though.
